// <auto-generated />
using System;
using Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220504160805_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Entidade.Ata", b =>
                {
                    b.Property<int>("NumeroAta")
                        .HasColumnType("int");

                    b.Property<int>("AnoAta")
                        .HasColumnType("int");

                    b.Property<int>("AnoPregao")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFinalVigencia")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataHomologacao")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataPublicacaoDOE")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataPublicacaoSistema")
                        .HasColumnType("date");

                    b.Property<double>("LimiteAdesao")
                        .HasColumnType("float");

                    b.Property<string>("NumeroPregao")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ObjetoResumido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Publicada")
                        .HasColumnType("bit");

                    b.HasKey("NumeroAta", "AnoAta");

                    b.ToTable("Atas");
                });
#pragma warning restore 612, 618
        }
    }
}
