// <auto-generated />
using System;
using Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Entidades.Ata", b =>
                {
                    b.Property<int>("CodigoAta")
                        .HasColumnType("int");

                    b.Property<int>("AnoAta")
                        .HasColumnType("int");

                    b.Property<int>("AnoPregao")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFinalVigencia")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataHomologacao")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataPublicacaoDOE")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataPublicacaoSistema")
                        .HasColumnType("date");

                    b.Property<double>("LimiteAdesao")
                        .HasColumnType("float");

                    b.Property<string>("NumeroPregao")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ObjetoResumido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Publicada")
                        .HasColumnType("bit");

                    b.HasKey("CodigoAta", "AnoAta");

                    b.ToTable("Atas");
                });

            modelBuilder.Entity("Dominio.Entidades.Detentora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("Varchar(18)");

                    b.Property<string>("Email")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Endereco")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Municipio")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("Varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Telefone")
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("Uf")
                        .HasColumnType("Varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Detentoras");
                });

            modelBuilder.Entity("Dominio.Entidades.DetentoraItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DetentoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DetentoraId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("DetentorasItens");
                });

            modelBuilder.Entity("Dominio.Entidades.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoAta")
                        .HasColumnType("int");

                    b.Property<int?>("AnoAta")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoAta")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CodigoAta")
                        .HasColumnType("int");

                    b.Property<int>("ConsumoEstimado")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Varchar(8000)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("NumeroItem")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoMercado")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("PrecoRegistrado")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UnidadeAquisicao")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAta", "AnoAta");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Dominio.Entidades.ParticipanteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnidadeAdministrativaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UnidadeAdministrativaId");

                    b.ToTable("ParticipantesItens");
                });

            modelBuilder.Entity("Dominio.Entidades.ProgramacaoConsumoParticipante", b =>
                {
                    b.Property<Guid>("ProgramacaoParticipanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Aditivo")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("ConsumoEstimado")
                        .HasColumnType("int");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("Transferido")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("ProgramacaoParticipanteId");

                    b.HasIndex("ParticipanteId")
                        .IsUnique();

                    b.ToTable("ProgamacaoConsumoParticipantes");
                });

            modelBuilder.Entity("Dominio.Entidades.UnidadeAdministrativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("EsferaAdministrativa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NomeUnidadeAdministrativa")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<bool>("OrgaoEx")
                        .HasColumnType("bit");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("UnidadeDaFederacao")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesAdministrativas");
                });

            modelBuilder.Entity("Dominio.Entidades.DetentoraItem", b =>
                {
                    b.HasOne("Dominio.Entidades.Detentora", "Detentora")
                        .WithMany("DetentorasItens")
                        .HasForeignKey("DetentoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Item", "Item")
                        .WithOne("DetentoraItem")
                        .HasForeignKey("Dominio.Entidades.DetentoraItem", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detentora");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Dominio.Entidades.Item", b =>
                {
                    b.HasOne("Dominio.Entidades.Ata", "Ata")
                        .WithMany("Itens")
                        .HasForeignKey("CodigoAta", "AnoAta");

                    b.Navigation("Ata");
                });

            modelBuilder.Entity("Dominio.Entidades.ParticipanteItem", b =>
                {
                    b.HasOne("Dominio.Entidades.Item", "Item")
                        .WithMany("ParticipantesItens")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.UnidadeAdministrativa", "UnidadeAdministrativa")
                        .WithMany("ParticipantesItens")
                        .HasForeignKey("UnidadeAdministrativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UnidadeAdministrativa");
                });

            modelBuilder.Entity("Dominio.Entidades.ProgramacaoConsumoParticipante", b =>
                {
                    b.HasOne("Dominio.Entidades.ParticipanteItem", "ParticipanteItem")
                        .WithOne("ProgramacoesConsumoParticipantes")
                        .HasForeignKey("Dominio.Entidades.ProgramacaoConsumoParticipante", "ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParticipanteItem");
                });

            modelBuilder.Entity("Dominio.Entidades.Ata", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Dominio.Entidades.Detentora", b =>
                {
                    b.Navigation("DetentorasItens");
                });

            modelBuilder.Entity("Dominio.Entidades.Item", b =>
                {
                    b.Navigation("DetentoraItem");

                    b.Navigation("ParticipantesItens");
                });

            modelBuilder.Entity("Dominio.Entidades.ParticipanteItem", b =>
                {
                    b.Navigation("ProgramacoesConsumoParticipantes");
                });

            modelBuilder.Entity("Dominio.Entidades.UnidadeAdministrativa", b =>
                {
                    b.Navigation("ParticipantesItens");
                });
#pragma warning restore 612, 618
        }
    }
}
